CONTROL_MANIFEST = (
    ("Navigation", "nav_dashboard", "Dashboard öffnen", "Route", "aktive Markierung", "test_navigation_routes_are_real"),
    ("Navigation", "nav_my_day", "Mein Tag öffnen", "Route", "aktive Markierung", "test_navigation_routes_are_real"),
    ("Navigation", "nav_inbox", "Eingang öffnen", "Route", "aktive Markierung", "test_navigation_routes_are_real"),
    ("Navigation", "nav_next_seven", "Nächste 7 Tage öffnen", "Route", "aktive Markierung", "test_navigation_routes_are_real"),
    ("Navigation", "nav_waiting", "Warten öffnen", "Route", "aktive Markierung", "test_navigation_routes_are_real"),
    ("Navigation", "nav_delegated", "Delegiert öffnen", "Route", "aktive Markierung", "test_navigation_routes_are_real"),
    ("Navigation", "nav_all_tasks", "Alle Aufgaben öffnen", "Route", "aktive Markierung", "test_navigation_routes_are_real"),
    ("Navigation", "nav_tasks", "Aufgabenliste öffnen", "Route", "aktive Markierung", "test_navigation_routes_are_real"),
    ("Navigation", "nav_kanban", "Kanban öffnen", "Route", "aktive Markierung", "test_shell_routes_use_real_boards"),
    ("Navigation", "nav_eisenhower", "Eisenhower öffnen", "Route", "aktive Markierung", "test_shell_routes_use_real_boards"),
    ("Navigation", "nav_calendar", "Kalender öffnen", "Route", "aktive Markierung", "test_shell_calendar_route_is_real"),
    ("Navigation", "nav_weekly_review", "Review öffnen", "Route", "aktive Markierung", "test_shell_weekly_review_route_is_real"),
    ("Navigation", "nav_settings", "Einstellungen öffnen", "Route", "aktive Markierung", "test_shell_exposes_real_settings_and_help_pages"),
    ("Navigation", "nav_help", "Hilfe öffnen", "Route", "aktive Markierung", "test_shell_exposes_real_settings_and_help_pages"),
    ("Schnellerfassung", "quick_capture_input", "Aufgabe erfassen", "neue Aufgabe", "Vorschau/gespeichert", "test_quick_capture_enter_saves_title_only_to_inbox"),
    ("Detail", "detail_title", "Titel bearbeiten", "Aufgabe", "Speicherstatus", "test_debounced_save_persists_latest_revision"),
    ("Detail", "detail_close", "Detail schließen", "Kontextpanel", "Wochenfokus", "test_detail_close_restores_weekly_focus"),
    ("Review", "review_back", "Schritt zurück", "Review-Schritt", "Schrittanzeige", "test_review_view_back_next_cancel_and_resume"),
    ("Review", "review_next", "Schritt weiter", "Review-Schritt", "Schrittanzeige", "test_completion_emits_summary_and_navigation"),
    ("Review", "review_cancel", "Review pausieren", "Sichtbarkeit", "später fortsetzbar", "test_review_view_back_next_cancel_and_resume"),
    ("Einstellungen", "settings_autostart", "Autostart wählen", "Konfiguration", "gespeichert", "test_settings_view_persists_and_controls_autostart"),
    ("Einstellungen", "settings_save", "Einstellungen speichern", "Konfiguration", "Gespeichert", "test_settings_view_persists_and_controls_autostart"),
)
